DeliveryCompany/Controllers/BoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DeliveryCompany.Models;
using Microsoft.AspNetCore.Authorization;

namespace DeliveryCompany.Controllers
{
    [Authorize]
    public class BoxController : Controller
    {
        private readonly DeliveryCompanyContext _context;

        public BoxController(DeliveryCompanyContext context)
        {
            _context = context;
        }

        // GET: Box
        public async Task<IActionResult> Index()
        {
            var deliveryCompanyContext = _context.Boxes.Include(b => b.Status);
            return View(await deliveryCompanyContext.ToListAsync());
        }

        // GET: Box/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var box = await _context.Boxes
                .Include(b => b.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (box == null)
            {
                return NotFound();
            }

            return View(box);
        }

        // GET: Box/Create
        public IActionResult Create()
        {
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Code");
            return View();
        }

        // POST: Box/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Uid,StatusId,Weight,Fragile,Dengerous,Height,Width,Depth,Comments")] Box box)
        {
            if (ModelState.IsValid)
            {
                _context.Add(box);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Code", box.StatusId);
            return View(box);
        }

        // GET: Box/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var box = await _context.Boxes.FindAsync(id);
            if (box == null)
            {
                return NotFound();
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Code", box.StatusId);
            return View(box);
        }

        // POST: Box/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Uid,StatusId,Weight,Fragile,Dengerous,Height,Width,Depth,Comments")] Box box)
        {
            if (id != box.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(box);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoxExists(box.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Code", box.StatusId);
            return View(box);
        }

        // GET: Box/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var box = await _context.Boxes
                .Include(b => b.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (box == null)
            {
                return NotFound();
            }

            return View(box);
        }

        // POST: Box/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var box = await _context.Boxes.FindAsync(id);
            _context.Boxes.Remove(box);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoxExists(int id)
        {
            return _context.Boxes.Any(e => e.Id == id);
        }
    }
}

DeliveryCompany/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DeliveryCompany.Models;
using Microsoft.AspNetCore.Authorization;

namespace DeliveryCompany.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private readonly DeliveryCompanyContext _context;

        public ClientController(DeliveryCompanyContext context)
        {
            _context = context;
        }

        // GET: Client
        public async Task<IActionResult> Index()
        {
            var deliveryCompanyContext = _context.Clients.Include(c => c.Address);
            return View(await deliveryCompanyContext.ToListAsync());
        }

        // GET: Client/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .Include(c => c.Address)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Client/Create
        public IActionResult Create()
        {
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "City");
            return View();
        }

        // POST: Client/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Uid,FirtsName,SecondName,LastName,AddressId,MailAdreess,Phone,CreateDate,UpdateDate,Active")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "City", client.AddressId);
            return View(client);
        }

        // GET: Client/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "City", client.AddressId);
            return View(client);
        }

        // POST: Client/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Uid,FirtsName,SecondName,LastName,AddressId,MailAdreess,Phone,CreateDate,UpdateDate,Active")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "City", client.AddressId);
            return View(client);
        }

        // GET: Client/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .Include(c => c.Address)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Client/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clients.Any(e => e.Id == id);
        }
    }
}

DeliveryCompany/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DeliveryCompany.Models;
using Microsoft.AspNetCore.Authorization;

namespace DeliveryCompany.Controllers
{
    [Authorize]
    public class TripController : Controller
    {
        private readonly DeliveryCompanyContext _context;

        public TripController(DeliveryCompanyContext context)
        {
            _context = context;
        }

        // GET: Trip
        public async Task<IActionResult> Index()
        {
            var deliveryCompanyContext = _context.Trips.Include(t => t.Box).Include(t => t.EndClientNavigation).Include(t => t.Operator).Include(t => t.StartClientNavigation);
            return View(await deliveryCompanyContext.ToListAsync());
        }

        // GET: Trip/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .Include(t => t.Box)
                .Include(t => t.EndClientNavigation)
                .Include(t => t.Operator)
                .Include(t => t.StartClientNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // GET: Trip/Create
        public IActionResult Create()
        {
            ViewData["BoxId"] = new SelectList(_context.Boxes, "Id", "Id");
            ViewData["EndClient"] = new SelectList(_context.Clients, "Id", "FirtsName");
            ViewData["OperatorId"] = new SelectList(_context.Employees, "Id", "FirtsName");
            ViewData["StartClient"] = new SelectList(_context.Clients, "Id", "FirtsName");
            return View();
        }

        // POST: Trip/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Uid,BoxId,StartClient,EndClient,OperatorId,TotalCost,CreateDate,DeliveredDate,Active")] Trip trip)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trip);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoxId"] = new SelectList(_context.Boxes, "Id", "Id", trip.BoxId);
            ViewData["EndClient"] = new SelectList(_context.Clients, "Id", "FirtsName", trip.EndClient);
            ViewData["OperatorId"] = new SelectList(_context.Employees, "Id", "FirtsName", trip.OperatorId);
            ViewData["StartClient"] = new SelectList(_context.Clients, "Id", "FirtsName", trip.StartClient);
            return View(trip);
        }

        // GET: Trip/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips.FindAsync(id);
            if (trip == null)
            {
                return NotFound();
            }
            ViewData["BoxId"] = new SelectList(_context.Boxes, "Id", "Id", trip.BoxId);
            ViewData["EndClient"] = new SelectList(_context.Clients, "Id", "FirtsName", trip.EndClient);
            ViewData["OperatorId"] = new SelectList(_context.Employees, "Id", "FirtsName", trip.OperatorId);
            ViewData["StartClient"] = new SelectList(_context.Clients, "Id", "FirtsName", trip.StartClient);
            return View(trip);
        }

        // POST: Trip/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Uid,BoxId,StartClient,EndClient,OperatorId,TotalCost,CreateDate,DeliveredDate,Active")] Trip trip)
        {
            if (id != trip.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trip);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TripExists(trip.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoxId"] = new SelectList(_context.Boxes, "Id", "Id", trip.BoxId);
            ViewData["EndClient"] = new SelectList(_context.Clients, "Id", "FirtsName", trip.EndClient);
            ViewData["OperatorId"] = new SelectList(_context.Employees, "Id", "FirtsName", trip.OperatorId);
            ViewData["StartClient"] = new SelectList(_context.Clients, "Id", "FirtsName", trip.StartClient);
            return View(trip);
        }

        // GET: Trip/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trip = await _context.Trips
                .Include(t => t.Box)
                .Include(t => t.EndClientNavigation)
                .Include(t => t.Operator)
                .Include(t => t.StartClientNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }

        // POST: Trip/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trip = await _context.Trips.FindAsync(id);
            _context.Trips.Remove(trip);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TripExists(int id)
        {
            return _context.Trips.Any(e => e.Id == id);
        }
    }
}

DeliveryCompany/Views/Shared/_ConfirmationPartial.cshtml
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Confirm Delivery
</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Delivery</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Trip Id</label>
                    <input id="tripId" type="text" class="form-control" required="required" name="tripId" />
                </div>
                <div class="form-group">
                    <label>Operator Id</label>
                    <input id="operatorId" type="text" class="form-control" required="required" name="tripId" />
                </div>
            </div>
            <div class="modal-footer">
                <button id="closeButton" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" onclick="onConfirmationSubmit()" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</div>

DeliveryCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeliveryCompany</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeliveryCompany</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="userComponent">
                            @await Component.InvokeAsync("UserComponent")
                        </li>
                        <li class="confButton">
                            @await Html.PartialAsync("_ConfirmationPartial.cshtml")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Address" asp-action="Index">Address</a>
                </li>
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Box" asp-action="Index">Box</a>
                </li>
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Client" asp-action="Index">Client</a>
                </li>
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                </li>
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                </li>
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                </li>
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Position" asp-action="Index">Position</a>
                </li>
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Status" asp-action="Index">Status</a>
                </li>
                <li>
                    <a class="nav-link text-info" asp-area="" asp-controller="Trip" asp-action="Index">Trip</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <a href="#menu-toggle" class="btn btn-primary" onclick="toogleMenu(event)">Toggle Menu</a>
                    <div class="col-lg-12">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DeliveryCompany - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>